### ISSUE TITLE
Field Type

### ISSUE THREAD

**Issue by shairyar** [craue/CraueConfigBundle#29]
Hi,

Great bundle and I am so glad to find it. I was wondering if it is possible to set the field type, for example if i want an option to display as a checkbox or dropdown menu how can i achieve it? I know the view to render the form is `modify_form.html.twig` but the fields that are being rendered are all `TextType`

**Comment by craue** [comment]
In short: the field type is fixed.

I'd like to keep the bundle as simple as it is. If your app has more complex requirements, you'll probably need a custom solution. See #5 for the discussion.

**Comment by shairyar** [comment]
What if we dont use the following way to render the form

```
{% for setting in form.settings if setting.section.vars.value == section %}
			{{ form_row(setting.name) }}
			{{ form_row(setting.section) }}
			{{ form_row(setting.value, {
					'label': setting.name.vars.value | trans({}, 'CraueConfigBundle'),
				}) }}
{% endfor %}
```
and use the following way to render the form with simple html

```
<input type="hidden" id="craue_config_modifySettings_settings_1_name"
                           name="craue_config_modifySettings[settings][1][name]" value="testing">
                    <input type="hidden" id="craue_config_modifySettings_settings_1_section"
                           name="craue_config_modifySettings[settings][1][section]" value="dummy">
                    <input type="text" id="craue_config_modifySettings_settings_1_value"
                           name="craue_config_modifySettings[settings][1][value]" class="form-control"
                           value="{{ form.settings.vars.data[1].value }}">
```

I am able to render a checkbox this way and get it to work :)

**Comment by craue** [comment]
Feel free to override the template. :smirk:

**Comment by shairyar** [comment]
This leads to one problem, each time you create a new field the order of the array gets changed so suppose you made the index 2 a checkbox, it will not longer be a checkbox as soon as you add a new field as the index as been replaced. One way of fixing this is by adding an id auto incremented field in entity and always pull entity byorder id this way the index will remain the same. Does symfony allow to override an entity or i will have to make this change inside the entity of your bundle?

**Comment by shairyar** [comment]
Okay so i made the change inside your entity by adding auto increment `id` after doing this i had to drop the schema and recreate it. Now i have checkbox, dropdown and text field on the form all are saving data and displaying the data correctly.

I still have a question though, now that i no longer am using the symfony form widget in twig, i hope this will not create any problem down the line, so far it seems to work perfectly.

Many thanks for the wonderful bundle.
